// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs6amrQx8yg0Kg2NgBVvbhEkjHq7Or2y4',
    appId: '1:627568050184:web:0786f25271dc526dbe11bd',
    messagingSenderId: '627568050184',
    projectId: 'asdfg-af5fc',
    authDomain: 'asdfg-af5fc.firebaseapp.com',
    storageBucket: 'asdfg-af5fc.appspot.com',
    measurementId: 'G-PXKSLFG404',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGsuaugkiypXE1dOiXFhpkAVmrx6fm5qo',
    appId: '1:627568050184:android:61856b50402c01f4be11bd',
    messagingSenderId: '627568050184',
    projectId: 'asdfg-af5fc',
    storageBucket: 'asdfg-af5fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoqqMXiNKE45Jrwfd0Bwskno0LlxC-hsY',
    appId: '1:627568050184:ios:bc37357538b0afb6be11bd',
    messagingSenderId: '627568050184',
    projectId: 'asdfg-af5fc',
    storageBucket: 'asdfg-af5fc.appspot.com',
    iosClientId: '627568050184-6hcdedoofbanvvqpnugmuihq1e2t0f3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNutritionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoqqMXiNKE45Jrwfd0Bwskno0LlxC-hsY',
    appId: '1:627568050184:ios:bc37357538b0afb6be11bd',
    messagingSenderId: '627568050184',
    projectId: 'asdfg-af5fc',
    storageBucket: 'asdfg-af5fc.appspot.com',
    iosClientId: '627568050184-6hcdedoofbanvvqpnugmuihq1e2t0f3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNutritionApp',
  );
}
